# Generated by Django 3.0.1 on 2020-01-04 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='gender',
            field=models.TextField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=40),
        ),
    ]
