# Generated by Django 3.0.1 on 2020-01-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='gender',
            field=models.TextField(choices=[('male', 'Male'), ('female', 'Female')], max_length=40),
        ),
    ]
